// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lyekka_impl.proto

#ifndef PROTOBUF_lyekka_5fimpl_2eproto__INCLUDED
#define PROTOBUF_lyekka_5fimpl_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "lyekka.pb.h"
// @@protoc_insertion_point(includes)

namespace Lyekka {
namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lyekka_5fimpl_2eproto();
void protobuf_AssignDesc_lyekka_5fimpl_2eproto();
void protobuf_ShutdownFile_lyekka_5fimpl_2eproto();


// ===================================================================


// ===================================================================

static const int kTreeShaExtFieldNumber = 1000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::Lyekka::pb::TreeRef,
    ::google::protobuf::internal::StringTypeTraits, 12, false >
  tree_sha_ext;
static const int kPartShaExtFieldNumber = 1000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::Lyekka::pb::Part,
    ::google::protobuf::internal::StringTypeTraits, 12, false >
  part_sha_ext;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace Lyekka

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lyekka_5fimpl_2eproto__INCLUDED
