// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "lyekka_impl.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Lyekka {
namespace pb {

namespace {


}  // namespace


void protobuf_AssignDesc_lyekka_5fimpl_2eproto() {
  protobuf_AddDesc_lyekka_5fimpl_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "lyekka_impl.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_lyekka_5fimpl_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_lyekka_5fimpl_2eproto() {
}

void protobuf_AddDesc_lyekka_5fimpl_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Lyekka::pb::protobuf_AddDesc_lyekka_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021lyekka_impl.proto\022\tLyekka.pb\032\014lyekka.p"
    "roto:)\n\014tree_sha_ext\022\022.Lyekka.pb.TreeRef"
    "\030\350\007 \001(\014:&\n\014part_sha_ext\022\017.Lyekka.pb.Part"
    "\030\350\007 \001(\014B\002H\001", 131);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lyekka_impl.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::Lyekka::pb::TreeRef::default_instance(),
    1000, 12, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::Lyekka::pb::Part::default_instance(),
    1000, 12, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_lyekka_5fimpl_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_lyekka_5fimpl_2eproto {
  StaticDescriptorInitializer_lyekka_5fimpl_2eproto() {
    protobuf_AddDesc_lyekka_5fimpl_2eproto();
  }
} static_descriptor_initializer_lyekka_5fimpl_2eproto_;

const ::std::string tree_sha_ext_default("");
::google::protobuf::internal::ExtensionIdentifier< ::Lyekka::pb::TreeRef,
    ::google::protobuf::internal::StringTypeTraits, 12, false >
  tree_sha_ext(kTreeShaExtFieldNumber, tree_sha_ext_default);
const ::std::string part_sha_ext_default("");
::google::protobuf::internal::ExtensionIdentifier< ::Lyekka::pb::Part,
    ::google::protobuf::internal::StringTypeTraits, 12, false >
  part_sha_ext(kPartShaExtFieldNumber, part_sha_ext_default);

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace Lyekka

// @@protoc_insertion_point(global_scope)
